"use strict";
(function(module){if(typeof define==='function'&&define.amd){define(['exports'],function(exports){module(exports);});}else if(typeof exports==='object'&&exports!==null&&typeof exports.nodeName!=='string'){module(exports);}else{module(typeof self!=='undefined'?self:this);}}(function(B){let Bw=2463534242,BN=()=>{let x=Bw;x^=x<<13;x^=x>>>17;x^=x<<5;Bw=x;return x;},BS=f=>(args,callback)=>{if(!args){args=[];}let javaArgs=Ba(H(),args.length);for(let i=0;i<args.length;++i){javaArgs.data[i]=K(args[i]);}B5(()=>{f.call(null,
javaArgs);},callback);},Cj=target=>target.$clinit=()=>{},Cc=obj=>{let cls=obj.constructor;let arrayDegree=0;while(cls.$meta&&cls.$meta.item){++arrayDegree;cls=cls.$meta.item;}let clsName="";if(cls.$meta.primitive){clsName=cls.$meta.name;}else {clsName=cls.$meta?cls.$meta.name||"a/"+cls.name:"@"+cls.name;}while(arrayDegree-->0){clsName+="[]";}return clsName;},E=superclass=>{if(superclass===0){return function(){};}if(superclass===void 0){superclass=H();}return function(){superclass.call(this);};},Bm=cls=>BQ(cls),H
=()=>D,Cf=()=>{return {$array:null,classObject:null,$meta:{supertypes:[],superclass:null}};},Bz=(name,binaryName)=>{let cls=Cf();cls.$meta.primitive=true;cls.$meta.name=name;cls.$meta.binaryName=binaryName;cls.$meta.enum=false;cls.$meta.item=null;cls.$meta.simpleName=null;cls.$meta.declaringClass=null;cls.$meta.enclosingClass=null;return cls;},Bn=Bz("char","C"),Cq=Bz("int","I"),Ba=(cls,sz)=>{let data=new Array(sz);data.fill(null);return new (T(cls))(data);},M=sz=>new B_(new Uint16Array(sz)),T=cls=>{let result
=cls.$array;if(result===null){function JavaArray(data){(H()).call(this);this.data=data;}JavaArray.prototype=Object.create((H()).prototype);JavaArray.prototype.type=cls;JavaArray.prototype.constructor=JavaArray;JavaArray.prototype.toString=function(){let str="[";for(let i=0;i<this.data.length;++i){if(i>0){str+=", ";}str+=this.data[i].toString();}str+="]";return str;};JavaArray.prototype.v=function(){let dataCopy;if('slice' in this.data){dataCopy=this.data.slice();}else {dataCopy=new this.data.constructor(this.data.length);for
(let i=0;i<dataCopy.length;++i){dataCopy[i]=this.data[i];}}return new (T(this.type))(dataCopy);};let name="["+cls.$meta.binaryName;JavaArray.$meta={item:cls,supertypes:[H()],primitive:false,superclass:H(),name:name,binaryName:name,enum:false,simpleName:null,declaringClass:null,enclosingClass:null};JavaArray.classObject=null;JavaArray.$array=null;result=JavaArray;cls.$array=JavaArray;}return result;},W,B2=strings=>{CB();W=new Array(strings.length);for(let i=0;i<strings.length;++i){W[i]=Bq(K(strings[i]));}},I
=index=>W[index],Bp=(array,offset,count)=>{let result="";let limit=offset+count;for(let i=offset;i<limit;i=i+1024|0){let next=Math.min(limit,i+1024|0);result+=String.fromCharCode.apply(null,array.subarray(i,next));}return result;},K=str=>str===null?null:Cv(str),Be=str=>str===null?null:str.i,CB=()=>(()=>{})(),Bq;
{Bq=str=>str;}let R=ex=>{throw CC(ex);},P=Symbol("javaException"),CC=ex=>{if(!ex.$jsException){BA(ex);}return ex.$jsException;},BA=ex=>{let javaCause=Cx(ex);let jsCause=javaCause!==null?javaCause.$jsException:void 0;let cause=typeof jsCause==="object"?{cause:jsCause}:void 0;let err=new F("Java exception thrown",cause);if(typeof Error.captureStackTrace==="function"){Error.captureStackTrace(err);}err[P]=ex;ex.$jsException=err;Cz(err,ex);},Cz=(err,ex)=>{if(typeof Cn==="function"&&err.stack){let stack=Cn(err.stack);let javaStack
=Ba(BT(),stack.length);let elem;let noStack=false;for(let i=0;i<stack.length;++i){let element=stack[i];elem=B7(K(element.className),K(element.methodName),K(element.fileName),element.lineNumber);if(elem==null){noStack=true;break;}javaStack.data[i]=elem;}if(!noStack){Co(ex,javaStack);}}},F;
if(typeof Reflect==='object'){let defaultMessage=Symbol("defaultMessage");F=function F(message,cause){let self=Reflect.construct(Error,[void 0,cause],F);Object.setPrototypeOf(self,F.prototype);self[defaultMessage]=message;return self;}
;F.prototype=Object.create(Error.prototype,{constructor:{configurable:true,writable:true,value:F},message:{get(){try {let javaException=this[P];if(typeof javaException==='object'){let javaMessage=BI(javaException);if(typeof javaMessage==="object"){return javaMessage!==null?javaMessage.toString():null;}}return this[defaultMessage];}catch(e){return "Exception occurred trying to extract Java exception message: "+e;}}}});}else {F=Error;}let B1=e=>e instanceof Error&&typeof e[P]==='object'?e[P]:null,BI=t=>Cr(t),Cx
=t=>CA(t),BT=()=>H(),B7=(className,methodName,fileName,lineNumber)=>{{return null;}},Co=(e,stack)=>{},Cb=outputFunction=>{let buffer="";return msg=>{let index=0;while(true){let next=msg.indexOf('\n',index);if(next<0){break;}outputFunction(buffer+msg.substring(index,next));buffer="";index=next+1;}buffer+=msg.substring(index);};},Ct=typeof $rt_putStdoutCustom==="function"?$rt_putStdoutCustom:typeof console==="object"?Cb(msg=>console.info(msg)):()=>{},BD=null,BL=data=>{let i=0;let packages=new Array(data.length);for
(let j=0;j<data.length;++j){let prefixIndex=data[i++];let prefix=prefixIndex>=0?packages[prefixIndex]:"";packages[j]=prefix+data[i++]+".";}BD=packages;},Cw=data=>{let packages=BD;let i=0;while(i<data.length){let cls=data[i++];cls.$meta={};let m=cls.$meta;let className=data[i++];m.name=className!==0?className:null;if(m.name!==null){let packageIndex=data[i++];if(packageIndex>=0){m.name=packages[packageIndex]+m.name;}}m.binaryName="L"+m.name+";";let superclass=data[i++];m.superclass=superclass!==0?superclass:null;m.supertypes
=data[i++];if(m.superclass){m.supertypes.push(m.superclass);cls.prototype=Object.create(m.superclass.prototype);}else {cls.prototype={};}let flags=data[i++];m.enum=(flags&8)!==0;m.flags=flags;m.primitive=false;m.item=null;cls.prototype.constructor=cls;cls.classObject=null;m.accessLevel=data[i++];let innerClassInfo=data[i++];if(innerClassInfo===0){m.simpleName=null;m.declaringClass=null;m.enclosingClass=null;}else {let enclosingClass=innerClassInfo[0];m.enclosingClass=enclosingClass!==0?enclosingClass:null;let declaringClass
=innerClassInfo[1];m.declaringClass=declaringClass!==0?declaringClass:null;let simpleName=innerClassInfo[2];m.simpleName=simpleName!==0?simpleName:null;}let clinit=data[i++];cls.$clinit=clinit!==0?clinit:function(){};let virtualMethods=data[i++];if(virtualMethods!==0){for(let j=0;j<virtualMethods.length;j+=2){let name=virtualMethods[j];let func=virtualMethods[j+1];if(typeof name==='string'){name=[name];}for(let k=0;k<name.length;++k){cls.prototype[name[k]]=func;}}}cls.$array=null;}},B5=(runner,callback)=>{let result;try {result
=runner();}catch(e){result=e;}if(typeof callback!=='undefined'){callback(result);}else if(result instanceof Error){throw result;}};
function D(){this.$id$=0;}
let Ch=a=>{let b,c,d,e,f,g,h,i,j,k,l,m,n;b=a;if(!b.$id$)b.$id$=BN();c=a.$id$;if(!c)d=I(0);else{if(!c)e=32;else{f=0;e=c>>>16|0;if(e)f=16;else e=c;g=e>>>8|0;if(!g)g=e;else f=f|8;h=g>>>4|0;if(!h)h=g;else f=f|4;g=h>>>2|0;if(!g)g=h;else f=f|2;if(g>>>1|0)f=f|1;e=(32-f|0)-1|0;}e=(((32-e|0)+4|0)-1|0)/4|0;i=M(e);j=i.data;e=(e-1|0)*4|0;k=0;while(e>=0){f=k+1|0;g=(c>>>e|0)&15;j[k]=g>=0&&g<16?(g<10?(48+g|0)&65535:((97+g|0)-10|0)&65535):0;e=e-4|0;k=f;}d=Ci(i);}b=Br();Bv(Bv(b,I(1)),d);l=new G;i=b.j;j=i.data;m=b.k;n=j.length;if
(m>=0&&m<=(n-0|0)){l.i=Bp(i.data,0,m);return l;}R(B6());},Bj=E(0),By=E(0);
function Bx(){D.call(this);this.u=null;}
let BQ=b=>{let c;if(b===null)return null;c=b.classObject;if(c===null){c=new Bx;c.u=b;b.classObject=c;}return c;},CE=E(),Ce=E();
function U(){let a=this;D.call(a);a.n=null;a.r=null;a.m=0;a.l=0;}
let CH=a=>{return a;},BF=a=>{BA(a);},Cr=a=>{return a.n;},CA=a=>{let b;b=a.r;if(b===a)b=null;return b;},Bd=E(U),J=E(Bd),B9=(a,b)=>{BF(a);a.m=1;a.l=1;a.n=b;},CG=a=>{let b=new J();B9(b,a);return b;},Cy=E(J),N=E(0),L=E(0),Q=E(0),G=E(),BZ=null,Ca=null,BO=null,BV=(a,b)=>{a.i=Bp(b.data,0,b.data.length);},Ci=a=>{let b=new G();BV(b,a);return b;},BK=(a,b)=>{a.i=b;},Cv=a=>{let b=new G();BK(b,a);return b;},BX=()=>{let b;BZ=M(0);b=new G;b.i="";Ca=b;BO=new Bl;},X=E(),B0=E(X),B4=null,BM=()=>{B4=Bm(Cq);};
function V(){let a=this;D.call(a);a.j=null;a.k=0;}
let B$=(a,b)=>{let c,d,e,f,g;c=a.j.data.length;if(c>=b)return;d=c>=1073741823?2147483647:Bo(b,Bo(c*2|0,5));e=a.j.data;f=M(d);b=e.length;if(d<b)b=d;g=f.data;c=0;while(c<b){g[c]=e[c];c=c+1|0;}a.j=f;},Bh=E(0),Bk=E(V),Cg=a=>{a.j=M(16);},Br=()=>{let a=new Bk();Cg(a);return a;},Bv=(a,b)=>{let c,d,e,f,g,h,i;c=a.k;d=a;b=b===null?I(2):b;e=d;if(c>=0&&c<=e.k){a:{b:{if(b===null)b=I(2);else if(b.i.length?0:1)break b;f=e.k+b.i.length|0;B$(e,f);g=e.k-1|0;while(g>=c){e.j.data[g+b.i.length|0]=e.j.data[g];g=g+(-1)|0;}e.k=e.k
+b.i.length|0;f=0;while(f<b.i.length){h=e.j;i=c+1|0;if(f<0)break a;if(f>=b.i.length)break a;h.data[c]=b.i.charCodeAt(f);f=f+1|0;c=i;}}return a;}R(B8());}b=new Y;Bg(b);R(b);},Cm=E(),BY=E(),BR=E(),BE=E(),S=()=>{S=Cj(BE);Cd();},BJ=b=>{let c,d,e;S();if(Z===null){c=new BB;d=null;e=null;c.s=d;c.q=Br();c.t=M(32);c.p=0;c.o=e;Z=c;}d=Z;BH(d,I(3));BH(d,I(4));},Cd=()=>{BX();BM();Cs();},Cp=E(),Cu=E(),Z=null,Bu=E(0),Bl=E(),BC=E(),B3=null,Ck=null,Cs=()=>{B3=Bm(Bn);Ck=Ba(BC,128);},Bt=E(0),Bs=E(0),BG=E(0),Bf=E();
function Bi(){Bf.call(this);this.s=null;}
function Bb(){let a=this;Bi.call(a);a.p=0;a.q=null;a.t=null;a.o=null;}
let Bc=E(Bb),BB=E(Bc),BH=(a,b)=>{if(b===null)b=I(2);Ct(Be(b));},BP=E(),BU=E(),O=E(J),Bg=a=>{BF(a);a.m=1;a.l=1;},B6=()=>{let a=new O();Bg(a);return a;},BW=E(),Y=E(O),CF=a=>{Bg(a);},B8=()=>{let a=new Y();CF(a);return a;},Cl=E(),Bo=(b,c)=>{if(b>c)c=b;return c;},CD=E();
BL([]);
Cw([D,0,0,[],0,3,0,0,0,Bj,0,D,[],3,3,0,0,0,By,0,D,[],3,3,0,0,0,Bx,0,D,[Bj,By],4,3,0,0,0,CE,0,D,[],4,3,0,0,0,Ce,0,D,[],4,3,0,0,0,U,0,D,[],0,3,0,0,0,Bd,0,U,[],0,3,0,0,0,J,0,Bd,[],0,3,0,0,0,Cy,0,J,[],0,3,0,0,0,N,0,D,[],3,3,0,0,0,L,0,D,[],3,3,0,0,0,Q,0,D,[],3,3,0,0,0,G,0,D,[N,L,Q],0,3,0,0,0,X,0,D,[N],1,3,0,0,0,B0,0,X,[L],0,3,0,0,0,V,0,D,[N,Q],0,0,0,0,0,Bh,0,D,[],3,3,0,0,0,Bk,0,V,[Bh],0,3,0,0,0,Cm,0,D,[],0,3,0,0,0,BY,0,D,[],0,3,0,0,0,BR,0,D,[],0,3,0,0,0,BE,0,D,[],0,3,0,S,0,Cp,0,D,[],4,3,0,0,0,Cu,0,D,[],4,3,0,0,0,Bu,
0,D,[],3,3,0,0,0,Bl,0,D,[Bu],0,3,0,0,0,BC,0,D,[L],0,3,0,0,0,Bt,0,D,[],3,3,0,0,0,Bs,0,D,[Bt],3,3,0,0,0,BG,0,D,[],3,3,0,0,0,Bf,0,D,[Bs,BG],1,3,0,0,0,Bi,0,Bf,[],0,3,0,0,0,Bb,0,Bi,[Bh],0,3,0,0,0,Bc,0,Bb,[],1,3,0,0,0,BB,0,Bc,[],0,3,0,0,0,BP,0,D,[],4,3,0,0,0,BU,0,D,[],4,3,0,0,0,O,0,J,[],0,3,0,0,0,BW,0,D,[L],1,3,0,0,0,Y,0,O,[],0,3,0,0,0,Cl,0,D,[],4,3,0,0,0,CD,0,D,[],0,3,0,0,0]);
let B_=T(Bn);
B2(["0","<java_object>@","null","Started","\n"]);
G.prototype.toString=function(){return Be(this);};
G.prototype.valueOf=G.prototype.toString;D.prototype.toString=function(){return Be(Ch(this));};
D.prototype.__teavm_class__=function(){return Cc(this);};
let C=BS(BJ);
C.javaException=B1;
B.main=C;}));
